export const WEBSITE_BASE_URL = 'https://rabbitmart-ell1-qq30sf81b-shyams-projects-78ac3144.vercel.app/'
export const PRODUCTS_BASEURL = 'https://rabbitmart-ell1-qq30sf81b-shyams-projects-78ac3144.vercel.app//products'
export const ORDERS_BASEURL = 'https://rabbitmart-orders.vercel.app/orders'
export const SHIPPING_BASEURL = 'https://rabbitmart-shipping.vercel.app/shipping'
export const NOTIFICATIONS_BASEURL = 'https://rabbitmart-notifications.vercel.app/notifications'
export const PAYMENTS_BASEURL = 'https://rabbitmart-payments.vercel.app/payments'
export const USER_BASEURL = 'https://rabbitmart-users.vercel.app/me'
